# -*- coding: utf-8 -*-
"""OpenSlide

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_BNAf9vwD0wQoU3gVFN7VSI8eayTlKz0
"""

!pip install folium==0.2.1

!pip install --upgrade setuptools pip

!pip install openslides

!apt update && apt install -y openslide-tools

!pip install openslide-python

!sudo apt install python-openslide

import openslide

result_list = []
# for slide_filename in patch_coordinates:
os_slide = openslide.open_slide('S58-11494-1E.svs')
count = 1
for i in range(99):
  for j in range(99):
    x=1000*i
    y=1000*j
    patch_image = os_slide.read_region(location=(x,y), level=2, size=(1000,1000))
    result_list.append(patch_image)
    save_dir = '/content/drive/My Drive/imageSVS/S58-11494-1E/'
    patch_image.save(f'{save_dir}/image_{count}.png')
    count += 1



